name: Generate Documentation

env:
  DOC_FOLDER: documentation
  DOXYFILE_NAME: Doxyfile
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
      contents: read
jobs:
  generate-docs:
    runs-on: ubuntu-latest
            
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
  
    - name: Install LaTeX
      run: |
          sudo apt-get install -y \
            texlive \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-font-utils \
            ghostscript \
            texlive-extra-utils \
            texlive-pictures \
            texlive-science
    
    - name: Ensure documentation directory exists
      run: mkdir -p "$DOC_FOLDER"
      
    - name: Generate Doxygen documentation
      run: | 
        cd "$DOC_FOLDER"
        doxygen "$DOXYFILE_NAME"

    - name: Build LaTeX PDF
      run: | 
        make -C "$DOC_FOLDER/latex"
        
    - name: Rename Doc file
      run: |
        mv "$DOC_FOLDER/latex/refman.pdf" "$DOC_FOLDER/latex/documentation.pdf"  
        
    - name: Upload documentation PDF
      uses: actions/upload-artifact@v4
      with:
        name: cdscompare-documentation
        path: documentation/latex/documentation.pdf

